### ISSUE TITLE
formatting questions

### ISSUE THREAD

**Issue by sagiegurari** [tbrand/cargo-tomlfmt#9]
I ran the tool and a file which I messed up the formatting to see how it works.
It didn't really fix some basic stuff, for example the below wasn't modified at all:

```toml
name = "cargo-make"
version="0.16.0"
readme =    "README.md"
license    = "Apache-2.0"
```

Also arrays sometimes are modified and sometimes it doesn't do anything.
I'm hoping I could have these things formatted properly and maybe even enable some config file to define what properly even means :)

also I saw that attributes are reordered, but i'm not sure I like abc like order instead of contextual order so I prefer to shut that off.

So I guess I'm asking here is

* can we setup rules for each formatting item I mentioned?
* have some external config file support?
* ability to disable reordering based on alphanumeric value (via config file...)?

Was looking for something like this crate for some time, so sorry if i'm pushing for too many things.

**Comment by tbrand** [comment]
Ok, at first, as you said, this crate does reordering by alphabetical order for all arrays basically.
But the 'package' table is skipped to do that since the order of them shouldn't be reordered.
https://github.com/tbrand/cargo-tomlfmt/blob/master/src/main.rs#L18
For example, I don't want to see 'edition' on top of the 'package' table.
I think that is why the unnecessary spaces remains.
So, for ideal, I would to keep the column orders in 'package' table but other stuffs are formatted. (Not implemented for now but just skip formatting the 'package' table.)

> can we setup rules for each formatting item I mentioned?

Not now for now.

> have some external config file support?

We could.

> ability to disable reordering based on alphanumeric value (via config file...)?

It could be.

Thanks for the feedback again. As a result, your feedback creates two new issues. Is that OK for you?
1. The formatting should be configured. Like change the rules of ordering.
2. The 'package' table is just skipped formatting for now. But it should be.

**Comment by sagiegurari** [comment]
ya, thanks
